### ISSUE TITLE
Pystoi as a dependency

### ISSUE THREAD

**Issue by mpariente** [nii-yamagishilab/Intelligibility-MetricGAN#1]
Dear authors, 

Thanks for open-sourcing your model ! 
I wonder, why not make `pystoi` a dependency of the project? Any reason? 

Thanks,

**Comment by hyli666** [comment]
@mpariente Hi,  I just noticed pystoi was implemented by you. Thanks for your work! I have updated README to let users install pystoi dependency.

This project was partially based on another people's codes. They manually added pystoi directory into their repository, that's why I did not make it as a dependency. Sorry for my mistake.

**Comment by mpariente** [comment]
Thanks ! :wink:
